### ISSUE TITLE
Not usable with latest yarn

### ISSUE THREAD

**Issue by thesabbir** [tophat/yarn-plugin-semver-up#13]
**Describe the bug**

Unable to use with the latest yarn.
Usage Error: Couldn't find a script named "semver".

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...

**To reproduce**
```
 yarn semver up --config semver-up.json --dry-run
```

**Expected behavior**
To give output without errors

**Screenshots**

**Environment **

- OS: MacOS 11.2.5
- Plugin Version: latest
- Node Version: latest
- Yarn Version: latest

@gtophat/yarn-plugin-licenses#14

**Comment by noahnu** [comment]
@thesabbir It should be fixed now, let me know.

I forgot to setup notifications for this repo, which is why I didn't see your reported issue sooner. Sorry about that.
