### ISSUE TITLE
What is the purpose of this plugin?

### ISSUE THREAD

**Issue by sebsobseb** [tophat/yarn-plugin-semver-up#17]
I just want to make sure I understand the purpose if this plugin corectly.

Yarn classic (Yarn 1)'s `yarn upgrade` command updates all the packages listed to the latest version (specified by the tag config), **respecting the semver constraints** of both your package and its dependencies.

Yarn berry (Yarn 2), replaced this command with `yarn up`, but this command simply update all the packages to the latest version **_without_ respecting the semver constraints** ranges.

So, this plugin allows Yarn 2 users to update their packages **respecting the semver constraints**.

Am I correct?
Thanks 🙏

**Comment by noahnu** [comment]
Yes.

Let's say your package.json looks like this:

```
"dependencies": {
    "react": "^16.0.0"
}
```

In Yarn Modern (v2+) running `yarn up react` may result in:

```
"dependencies": {
    "react": "^18.4.5"
}
```

however that means you've accepted a breaking change in react. Now imagine if you're updating quite a number of dependencies at once, across multiple workspaces. You don't want to have to read through the breaking changes for each package. `yarn semver up` will help you adopt changes more gradually. With `yarn semver up` after `yarn semver up react`, you'll get:

```
"dependencies": {
    "react": "^16.14.0"
}
```

You can also setup rules to group related dependencies together, which can be useful to write a basic version of dependabot/renovate in a github action.

**Comment by sebsobseb** [comment]
Thank you @noahnu for the confirmation. That's exactly the issue we're facing.

Do you know why Yarn (v2+) decided to stop supporting semver ranges? I mean isn't that the point of a package manager? This looks like a real downgrade for us.

**Comment by noahnu** [comment]
It still installs packages by respecting semver. It's just the yarn up command missing this feature. I'd recommend opening a feature request / discussion on the Yarn Modern repository.

**Comment by noahnu** [comment]
I don't recall. Just tried searching for it and didn't see an issue. Feel free to go ahead and create an issue. I'm personally happy maintaining this plugin. It's relatively low effort.
